### PR TITLE
[SVN] Fix 'octave-cli' not recognizing 'qt' as a plot toolkit.

### LINKED ISSUE #3: Octave session error due to "octave-cli" not recognizing "qt" as a plot toolkit on Linux
# Problem description

In an octave sesion, when executing a (any) command, throw an error:

>error: feval: /usr/lib/octave/5.2.0/oct/x86_64-pc-linux-gnu/__init_fltk__.oct: failed to load: libfltk_gl.so.1.3: cannot open shared object file: No such file or directory
error: called from
    graphics_toolkit at line 91 column 5
    figure at line 91 column 7
    gcf at line 63 column 9
    tmrepl at line 41 column 21
    ~/.TeXmacs/plugins/octave/octave/tmstart.m at line 47 column 1
warning: gh_manager::do_close_all_figures: some graphics elements failed to close.

# Problem reproduction

- Without fltk or gnuplot installed on the system. By default, octave will use qt as the plot engine.
- Open TeXmaxs, open an octave session, execuate any command

# Problem attribution

From /octave/progs/init-octave.scm, it seems that the command to open a new octave instance is "octave-cli". I tried to execute "available_graphics_toolkits", the result is

>ans =
{
  [1,1] = fltk
}.

Also, the result of command "graphics_toolkit" in octave is

>ans = fltk.

After I searched for any similar issue, I found [this](https://stackoverflow.com/questions/47777354/octave-cli-does-not-recognize-qt-graphics-toolkit). Perhaps it's because octave-cli does not recognize "qt" as a plot toolkit.

# Possible solution

- Use "octave --no-gui" as the command to create a new octave instance.
- Install fltk or gnuplot package

### PR DESCRIPTION
**Pull request by walwan**
Tested on 5.8.18-1-MANJARO with all commands given in the demo part in the plugin manual.
Need more testing.
Fixes #3

### CODE REVIEW

**Comment by da-liii** [comment]
If there are no available backends, we may fallback to qt. By default, using `octave-cli` is a good choice.

As you have mentioned in #3:

> One thing to mention, a window will flash after running the first command.

Also, we may document about the unexpected flash under the `doc/`.

**Comment by AFMiJ** [comment]
Unfortunately, when using the Octave.app on OSX, only the qt graphics toolkit is available.
Then, calling Octave with octave-cli, no graphic toolkit is loaded. Invoking a graphic command blocks the plugins, see image below.

OSX_octave-cli

Changing the init-octave.scm file as below

        ;(string-append "octave-cli -qi " boot)
        (string-append "octave -qi " boot)

resolve this issue (see image).

OSX_octave

I do not remember what happens if octave is installed through Homebrew, though.

**Comment by da-liii** [comment]
@AFMiJ  

```
brew install gnuplot
```
Providing the `gnuplot` backend will make it work.

**Comment by da-liii** [comment]
Let me merge this PR. @walwan  if you have time, please create an issue of the unexpected flash.

**Comment by walwan** [comment]
@sadhen Thanks! I'll create an issue concerning the unexpected flash.

**Pull request closed without merging**
